#!/bin/bash
set -e

echo "Pre-commit checks starting..."
bun run tsc
cargo fmt --all -- --check
cargo clippy --all-targets --all-features -- -D warnings -D clippy::all -D clippy::pedantic -D clippy::nursery
